#define SERIAL_SPEED 1000000

#define ENCODER_CLK_PIN 16
#define ENCODER_DT_PIN 4
#define ENCODER_BTN_PIN 17

#define IR_RECEIVE_PIN 27

#define WS2812B_PIN 26
#define NUM_LEDS 230

#define I2S_BCK_PIN 25
#define I2S_DATA_OUT_PIN 33
#define I2S_WS_PIN 32

#define SAMPLES_SIZE 2048

#define BLUETOOTH_DEVICE_NAME "Koba Audio Receiver"

#define DEFAULT_MODE COLOR_MUSIC_MODE
#define BRIGHT_STEP 10

#define LED_STRIP_TASK_PRIORITY 5
#define LED_STRIP_TASK_STACK_SIZE 2048

#define COLOR_MUSIC_TASK_PRIORITY 13
#define COLOR_MUSIC_TASK_STACK_SIZE 2048

#define SERIAL_PORT_INTERACTION_TASK_PRIORITY 1
#define SERIAL_PORT_INTERACTION_TASK_STACK_SIZE 2048